package Interfaces;

/**
 * Created by Nibbla on 27.09.2017.
 */
public enum Workmode {
     SYSTEMOUT,  SHOWASTAR, SHOWTESSELATED, SYSTEMOUTARCHIVE, SHOWKLASSIFIED, SIMPLECLASSIFICATORANDNOTJODISPECIALSAUCE, JODISPECIALSAUCEANDNOTSIMPLECLASSIFICATOR, SHOWSENSOR
}
